import type { Theme } from 'theme-ui';

export const theme: Theme = {
  colors: {
    // brand palette
    primary: '#101828',
    secondary: '#344053',
    'text-tertiary': '#657085',
    'gray-25': '#F8F9FA',
    'gray-50': '#F6F7F9',
    'gray-100': '#F2F3F7',
    'gray-200': '#E9EBEF',
    'gray-300': '#CED4DC',
    'gray-400': '#97A1B1',
    'gray-500': '#656F84',
    'gray-600': '#465266',
    'gray-700': '#333F53',
    'gray-800': '#1C2838',
    'gray-900': '#0E1727',
    'purple-25': '#FBF9FE',
    'purple-50': '#F8F5FF',
    'purple-100': '#F3EAFE',
    'purple-200': '#E8D6FD',
    'purple-300': '#D5B9FA',
    'purple-400': '#B591F5',
    'purple-500': '#9D76EC',
    'purple-600': '#8057DB',
    'purple-700': '#693FC6',
    'purple-800': '#52379D',
    'purple-900': '#402E7D',
    'purple-opacity-5': 'rgba(128, 87, 219, 0.05)',
    'purple-opacity-15': 'rgba(128, 87, 219, 0.15)',
    'warning-red-1': '#FB483A',
    'warning-red-2': '#FFE5E3',
    'warning-red-3': '#FFF4F3',
    'warning-green-1': '#049955',
    'warning-green-2': '#D2FBE0',
    'warning-green-3': '#EDFDF4',
    'warning-yellow-1': '#FFB800',
    'warning-yellow-2': '#FEF1C8',
    'warning-yellow-3': '#FFFBEC',
    'warning-orange-1': '#FF7612',
    'warning-orange-2': '#FFD7BA',
    'warning-orange-3': '#FFF1E6',

    // semantic aliases used across app components
    text: '#101828',
    background: '#F8F9FA',
    surface: '#FFFFFF',
    border: '#CED4DC',
    error: '#FB483A',
    muted: '#F2F3F7',
  },
  fonts: {
    body: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    heading: 'inherit',
    monospace: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  },
  fontSizes: ['12px', '14px', '16px', '20px', '24px', '32px', '40px', '48px'],
  space: [
    '0',
    '4px',
    '8px',
    '16px',
    '24px',
    '32px',
    '40px',
    '48px',
    '64px',
    '80px',
    '96px',
    '112px',
    '128px',
  ],
  breakpoints: ['544px', '768px', '992px', '1200px'],
  radii: { none: 0, sm: '4px', md: '8px', lg: '12px' },
  shadows: {
    card: '0 1px 3px rgba(16, 24, 40, 0.08), 0 1px 2px rgba(16, 24, 40, 0.04)',
    focus: '0 0 0 3px rgba(128, 87, 218, 0.15)',
  },
  buttons: {
    primary: {
      display: 'flex',
      padding: '9px 17px',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '8px',
      borderRadius: '12px',
      background: 'purple-600',
      textAlign: 'center',
      color: '#fff',
      border: '1px solid',
      borderColor: 'transparent',
      fontFamily: 'inherit',
      fontSize: '16px',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '24px',
      whiteSpace: 'nowrap',
      cursor: 'pointer',
      userSelect: 'none',
      appearance: 'none',
      textDecoration: 'none',
      transition: 'background-color .24s, box-shadow .24s',
      '&:hover:not(:active):not(:disabled)': {
        textDecoration: 'none',
        backgroundColor: 'purple-700',
      },
      '&:focus': {
        outline: 'none',
        backgroundColor: 'purple-600',
        boxShadow: '0px 0px 0px 3px rgba(128, 87, 219, 0.40)',
      },
      '&:active': {
        backgroundColor: 'purple-800',
      },
      '&:disabled': {
        cursor: 'default',
        backgroundColor: 'purple-500',
      },
    },
    secondary: {
      display: 'flex',
      padding: '9px 17px',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '8px',
      background: 'purple-50',
      borderRadius: '12px',
      color: 'purple-700',
      border: '1px solid',
      borderColor: 'transparent',
      fontFamily: 'inherit',
      fontSize: '16px',
      fontWeight: 600,
      lineHeight: '24px',
      whiteSpace: 'nowrap',
      cursor: 'pointer',
      userSelect: 'none',
      appearance: 'none',
      textDecoration: 'none',
      transition: 'background-color .24s, box-shadow .24s',
      '&:hover:not(:active):not(:disabled)': { backgroundColor: 'purple-100' },
      '&:focus': {
        outline: 'none',
        backgroundColor: 'purple-50',
        boxShadow: '0px 0px 0px 3px #F3EAFE',
      },
      '&:active': { backgroundColor: 'purple-200' },
      '&:disabled': {
        cursor: 'default',
        color: 'purple-300',
        backgroundColor: 'purple-25',
      },
    },
    border: {
      display: 'flex',
      padding: '9px 17px',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '8px',
      background: '#fff',
      borderRadius: '12px',
      textAlign: 'center',
      color: 'secondary',
      border: '1px solid',
      borderColor: 'gray-300',
      fontFamily: 'inherit',
      fontSize: '16px',
      fontWeight: 600,
      lineHeight: '24px',
      whiteSpace: 'nowrap',
      cursor: 'pointer',
      userSelect: 'none',
      appearance: 'none',
      textDecoration: 'none',
      transition: 'background-color .24s, box-shadow .24s',
      '&:hover:not(:active):not(:disabled)': {
        backgroundColor: 'gray-50',
        borderColor: 'gray-300',
      },
      '&:focus': {
        outline: 'none',
        backgroundColor: '#fff',
        borderColor: 'gray-300',
        boxShadow: '0px 0px 0px 3px rgba(206, 212, 220, 0.40)',
      },
      '&:active': { backgroundColor: 'gray-100', borderColor: 'gray-300' },
      '&:disabled': {
        cursor: 'default',
        color: 'gray-300',
        backgroundColor: 'gray-25',
        borderColor: 'gray-200',
      },
    },
    tertiary: {
      display: 'flex',
      padding: '9px 17px',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '8px',
      background: 'gray-50',
      borderRadius: '12px',
      textAlign: 'center',
      color: 'secondary',
      border: '1px solid',
      borderColor: 'transparent',
      fontFamily: 'inherit',
      fontSize: '16px',
      fontWeight: 600,
      lineHeight: '24px',
      whiteSpace: 'nowrap',
      cursor: 'pointer',
      userSelect: 'none',
      appearance: 'none',
      textDecoration: 'none',
      transition: 'background-color .24s, box-shadow .24s',
      '&:hover:not(:active):not(:disabled)': { backgroundColor: 'gray-100' },
      '&:focus': {
        outline: 'none',
        backgroundColor: '#fff',
        boxShadow: '0px 0px 0px 3px rgba(206, 212, 220, 0.40)',
      },
      '&:active': { backgroundColor: 'gray-200' },
      '&:disabled': {
        cursor: 'default',
        color: 'gray-300',
        backgroundColor: 'gray-50',
      },
    },
    invisible: {
      display: 'flex',
      padding: '9px 17px',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '8px',
      background: 'transparent',
      borderRadius: '4px',
      textAlign: 'center',
      color: 'purple-600',
      border: '1px solid',
      borderColor: 'transparent',
      fontFamily: 'inherit',
      fontSize: '16px',
      fontWeight: 500,
      lineHeight: '24px',
      whiteSpace: 'nowrap',
      cursor: 'pointer',
      userSelect: 'none',
      appearance: 'none',
      textDecoration: 'none',
      transition: 'background-color .24s, box-shadow .24s',
      '&:hover:not(:active):not(:disabled)': { color: 'gray-900' },
      '&:focus': {
        outline: 'none',
        color: 'purple-600',
        boxShadow: '0px 0px 0px 3px rgba(206, 212, 220, 0.40)',
      },
      '&:active': { color: 'gray-900' },
      '&:disabled': {
        cursor: 'default',
        color: 'gray-400',
        pointerEvents: 'none',
      },
    },
    link: {
      display: 'flex',
      padding: '9px 17px',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '8px',
      borderRadius: '12px',
      background: 'transparent',
      textAlign: 'center',
      color: 'secondary',
      border: '1px solid',
      borderColor: 'transparent',
      fontFamily: 'inherit',
      fontSize: '16px',
      fontWeight: 600,
      lineHeight: '24px',
      whiteSpace: 'nowrap',
      cursor: 'pointer',
      userSelect: 'none',
      appearance: 'none',
      textDecoration: 'none',
      transition: 'background-color .24s, box-shadow .24s',
      '&:hover:not(:active):not(:disabled)': { color: 'gray-300' },
      '&:focus': {
        outline: 'none',
        color: 'secondary',
        boxShadow: '0px 0px 0px 3px rgba(206, 212, 220, 0.40)',
      },
      '&:active': { color: 'gray-300' },
      '&:disabled': { cursor: 'default', color: 'gray-300' },
    },
    'warning-red': {
      display: 'flex',
      padding: '9px 17px',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '8px',
      borderRadius: '12px',
      background: 'warning-red-1',
      textAlign: 'center',
      color: '#fff',
      border: '1px solid',
      borderColor: 'transparent',
      fontFamily: 'inherit',
      fontSize: '16px',
      fontWeight: 600,
      lineHeight: '24px',
      whiteSpace: 'nowrap',
      cursor: 'pointer',
      userSelect: 'none',
      appearance: 'none',
      textDecoration: 'none',
      transition: 'background-color .24s, box-shadow .24s',
      '&:hover:not(:active):not(:disabled)': {
        backgroundColor: 'warning-red-1',
      },
      '&:focus': {
        outline: 'none',
        backgroundColor: 'warning-red-1',
        boxShadow: '0px 0px 0px 3px #FFE5E3',
      },
      '&:active': { backgroundColor: '#E13F34' },
      '&:disabled': {
        cursor: 'default',
        backgroundColor: 'warning-red-1',
        opacity: '0.8',
      },
    },
  },
  forms: {
    input: {
      boxShadow: '0px 1px 2px 0px rgba(16, 24, 40, 0.05)',
      transition: 'border-color .24s, background-color .24s, box-shadow .24s',
      height: '44px',
      background: '#fff',
      border: '1px solid',
      borderColor: 'gray-300',
      borderRadius: '8px',
      outline: 'none',
      padding: '10px 14px',
      fontStyle: 'normal',
      fontSize: '16px',
      fontWeight: 400,
      lineHeight: '24px',
      color: 'primary',
      '&::placeholder': { color: '#657085', opacity: 1 },
      '&:focus-within': {
        borderColor: 'purple-600',
        boxShadow: '0px 0px 0px 3px rgba(128, 87, 218, 0.15)',
      },
      '&:disabled': {
        borderColor: 'gray-300',
        backgroundColor: 'gray-50',
        boxShadow: '0px 1px 2px 0px rgba(16, 24, 40, 0.05)',
      },
    },
  },
  styles: {
    root: {
      fontFamily: 'body',
      color: 'text',
      bg: 'background',
      margin: 0,
      minHeight: '100vh',
    },
  },
};
